# Generated by Django 6.0.1 on 2026-01-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
    ]
