# Generated by Django 5.2.10 on 2026-02-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_discount'),
    ]

    operations = [
    ]
