# Generated by Django 5.2.10 on 2026-02-07 08:08

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20260207_1305'),
    ]

    operations = [
        TrigramExtension(),
    ]
